### ISSUE TITLE
Script halts after successful crack with JSONDecodeError

### ISSUE THREAD

**Issue by l3pr-org** [Banthex/help_crack_banthex#10]
### Description:
Upon successful cracking of a hash using the help_crack_banthex.py script, the script persistently halts (crash upon rerun of script) with a JSONDecodeError. The error occurs when the script attempts to print a response that is expected to be in JSON format. This error seems to be originating from the requests library when it attempts to decode the response from an HTTP request.

### Steps to Reproduce:
  
    Ensure a working hashcat installation.
    Ensure all dependencies are installed (including tqdm).
    Run the main Python script ./help_crack_banthex.py.
    Start the cracking process and wait for a successful crack.
    Observe the script halting after the successful crack with the JSONDecodeError.

### Expected Behavior:
The script should handle successful cracks gracefully and continue execution without errors.

### Actual Behavior:
The script halts with a JSONDecodeError after a successful crack.

### Additional Information:

    Python version: 3.11.8 (python --version : Python 3.11.8)
    Operating System: Manjaro Linux, kernel 6.6.26-1-MANJARO (64-bit)
    Hashcat version: 6.2.3 (hashcat --version : v6.2.3)

### stdout

[many other unsuccessful cracks above, truncated as the hascat output is redundant]
Session..........: hashcat
Status...........: Cracked
Hash.Name........: WPA-EAPOL-PBKDF2
Hash.Target......: Zocker-WG (AP:14:6e:0a:4a:e8:fe STA:18:de:50:a7:38:06)
Time.Started.....: Fri May 10 13:42:06 2024 (2 secs)
Time.Estimated...: Fri May 10 13:42:08 2024 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (wpskey2.txt)
Guess.Queue......: 4/15 (26.67%)
Speed.#1.........:   436.8 kH/s (10.51ms) @ Accel:4 Loops:128 Thr:1024 Vec:1
Recovered........: 1/1 (100.00%) Digests
Progress.........: 942080/1000000 (94.21%)
Rejected.........: 0/942080 (0.00%)
Restore.Point....: 753664/1000000 (75.37%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: 27536643 -> 29420797
Hardware.Mon.#1..: Temp: 45c Fan: 99% Util: 95% Core:1980MHz Mem:6800MHz Bus:16

Started: Fri May 10 13:41:59 2024
Stopped: Fri May 10 13:42:08 2024
Incrementing dictcount to 2, last duration 9s
Key for bssid 14:6e:0a:4a:e8:fe is: 29163632
503
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<redacted for privacy>/crackwpa/banthex/./help_crack_banthex.py", line 986, in <module>
    hc.run()
  File "/home/<redacted for privacy>/crackwpa/banthex/./help_crack_banthex.py", line 927, in run
    print(response.json())
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks, ChatGPT :smile:

**Comment by Banthex** [comment]
Great thanks for your report.
The https://github.com/Banthex/help_crack_banthex/blob/master/help_crack_banthex.py is not in a working state because the gamipress api key is missing. If you want to use the leaderboard from banthex.de then use https://github.com/Banthex/help_crack_banthex/blob/master/installer.py:
Automatic Installation

    Download the installer script: https://github.com/Banthex/help_crack_banthex/blob/master/installer.py.
    Execute pip install tqdm if necessary.
    Run installer.py to automatically download and install the required dependencies.
    Run chmod a+x help_crack_banthex.
    Start the program with ./help_crack_banthex.

If you dont want to use the binary u can simply use https://wpa-sec.stanev.org/

**Comment by l3pr-org** [comment]
I did run installer.py. Do I have to hardcode an API key somewhere?

**Comment by Banthex** [comment]
Type hashcat -v. Do u get the version 6.2.3 back? Is there the ./help_crack_banthex binary (without .py?)

**Comment by l3pr-org** [comment]
Yep, as per my original post:
>     Hashcat version: 6.2.3 (hashcat --version : v6.2.3)

> Is there the ./help_crack_banthex binary (without .py?)

I do not have a non-python 'help_crack_banthex.'

**Comment by Banthex** [comment]
Ah weired maybe a bug with the installer please use this: https://github.com/Banthex/help_crack_banthex/releases/download/V1.1_Linux/help_crack_banthex

**Comment by l3pr-org** [comment]
Precompiled binary works perfectly! Thanks. I'll leave this issue open as it is not solved.

**Comment by Banthex** [comment]
Its solved because the python file will not work. Its the sourcecode without the api for gamipress. (wordpress plugin)
